{
 "title": "T-RMM Agent Dashboard",
 "description": "Agent Dashboard",
 "tags": [ "TRMMAgentDashboard" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Client",
    "query": "SELECT name FROM clients_client order by name"
   },
   { "name": "Sites", "query": "SELECT name FROM clients_site" },
   {
    "name": "Agent",
    "query": "SELECT \nhostname\nFROM \nagents_agent\n\n"
   },
   { "name": "Tactical", "query": "postgres" },
   { "name": "WindowsExp", "query": "prometheus" },
   {
    "name": "server",
    "label": "Agent_IP",
    "query": "SELECT\nnetwork_config->0->>'IPAddress' as \"IP Address\"\nFROM agents_agent\ncross join lateral jsonb_array_elements(wmi_Detail->'network_config') as network_config\nWHERE (hostname in($Agent)) and (network_config->0->>'DefaultIPGateway' is not null) and (($Agent) <> 'All')"
   }
  ]
 },
 "panels": [
  { "title": "Quick Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n  concat('Site: ',clients_site.name,' / HostName: ', agents_agent.hostname,' ',agents_agent.DESCRIPTION)\nfrom \n  agents_agent\n  LEFT OUTER JOIN clients_site on agents_agent.site_id = clients_site.id\n  where \n    agents_agent.hostname = $Agent"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  concat(\r\n          to_char(now() - to_timestamp(boot_time) ,'DD' ),' Days ', \r\n          to_char(now() - to_timestamp(boot_time),'HH24' ), ' Hours ',\r\n          to_char(now() - to_timestamp(boot_time),'MI' ), ' Minutes '\r\n        )\r\nFrom \r\n  agents_agent\r\nWhere\r\n  agents_agent.hostname = $Agent"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 2 },
   "targets": [
    {
     "rawSql": "select   \r\nCASE\r\n  WHEN (count(*) = 1) THEN 'Connected'\r\n  WHEN (count(*) = 0) THEN 'No Connected'\r\n  ELSE ''\r\n END AS modifiedpvc\r\n  \r\n from \r\n  agents_agent\r\n where \r\n   agents_agent.hostname = $Agent  and\r\n   last_seen > NOW()- interval '1 hours'\r\n "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT\n  CASE\n   WHEN (has_patches_pending = true) THEN 'System not up to date'\n    WHEN (has_patches_pending = false) THEN 'System up to date'\n  ELSE 'nothing'\n END AS  Status\nFROM \n  agents_agent\nwhere\n     agents_agent.hostname = $Agent"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 2 },
   "targets": [
    {
     "rawSql": "select\n  CASE\n   WHEN (agents_agent.needs_reboot = true) THEN 'Reboot required'\n    WHEN (agents_agent.needs_reboot = false) THEN 'No reboot required'\n  ELSE 'nothing'\n END AS  Status\nFrom \n  agents_agent\nWhere\n  agents_agent.hostname = $Agent\n"
    }
   ]
  },
  {
   "title": "CPU Model",
   "type": "stat",
   "description": "Type of CPU installed",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 2 },
   "targets": [
    {
     "rawSql": "select  \r\n  concat(wmi_detail->'cpu'->0->0->>'Name',' \\ ',wmi_detail->'base_board'->0->0->>'Manufacturer')\r\nfrom \r\n  agents_agent\r\nwhere \r\n   agents_agent.hostname = $Agent"
    }
   ]
  },
  {
   "title": "System Ram",
   "type": "stat",
   "description": "Total Agent Memory",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select   \r\n   concat((total_ram),'GB / ',concat(wmi_detail->'mem'->0->0->>'Speed','MHz'))\r\n  \r\nfrom \r\n  agents_agent\r\nwhere \r\n  agents_agent.hostname = $Agent"
    }
   ]
  },
  {
   "title": "Operating System",
   "type": "stat",
   "description": "Agent Operating System",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select   \r\n  concat(SUBSTRING(agents_agent.operating_system,'(.*),'),' ', wmi_detail->'cpu'->0->0->>'DataWidth',' Bit') \r\n  \r\nfrom \r\n  agents_agent\r\nwhere \r\n     agents_agent.hostname = $Agent\r\n"
    }
   ]
  },
  {
   "title": "Available Disk Space",
   "type": "table",
   "description": "Free disk space per drive",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "select \r\n  concat(items.device,'\\ ', items.free,' free on ',items.total)\r\nfrom \r\n  agents_agent,\r\n  jsonb_to_recordset(disks) as items(device text, free text, total text)\r\nWhere\r\n  agents_agent.hostname = $Agent"
    }
   ]
  },
  {
   "title": "Total Storage Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "select\r\n  disks->0->>'percent' as \"Occupation\"\r\nfrom \r\n  agents_agent\r\nwhere \r\n  agents_agent.hostname = $Agent\r\n"
    }
   ]
  },
  {
   "title": "Virtual memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(windows_os_virtual_memory_bytes{instance=~\"$server.*\"} - windows_os_virtual_memory_free_bytes{instance=~\"$server.*\"}) / windows_os_virtual_memory_bytes{instance=~\"$server.*\"} * 100"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(windows_cpu_time_total{mode=\"idle\", instance=~\"$server.*\"}[$__interval])) * 100)"
    }
   ]
  },
  {
   "title": "Physical memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(windows_cs_physical_memory_bytes{instance=~\"$server.*\"} - windows_os_physical_memory_free_bytes{instance=~\"$server.*\"}) / windows_cs_physical_memory_bytes{instance=~\"$server.*\"} * 100"
    }
   ]
  },
  {
   "title": "Windows Version",
   "type": "stat",
   "description": "Agent Operating System Version",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "windows_os_info{instance=~\"$server.*\"}",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "CPU load %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 / sum(rate(windows_cpu_time_total{instance=~\"$server.*\"}[$__rate_interval])) * sum(rate(windows_cpu_time_total{instance=~\"$server.*\", mode=\"dpc\"}[$__rate_interval]))",
     "legendFormat": "dpc"
    },
    {
     "expr": "100 / sum(rate(windows_cpu_time_total{instance=~\"$server.*\"}[$__rate_interval])) * sum(rate(windows_cpu_time_total{instance=~\"$server.*\", mode=\"interrupt\"}[$__rate_interval]))",
     "legendFormat": "interrupt"
    },
    {
     "expr": "100 / sum(rate(windows_cpu_time_total{instance=~\"$server.*\"}[$__rate_interval])) * sum(rate(windows_cpu_time_total{instance=~\"$server:9182.*\", mode=\"privileged\"}[$__rate_interval]))",
     "legendFormat": "privileged"
    },
    {
     "expr": "100 / sum(rate(windows_cpu_time_total{instance=~\"$server.*\"}[$__rate_interval])) * sum(rate(windows_cpu_time_total{instance=~\"$server.*\", mode=\"user\"}[$__rate_interval]))",
     "legendFormat": "user"
    },
    {
     "expr": "100 / sum(rate(windows_cpu_time_total{instance=~\"$server.*\"}[$__rate_interval])) * sum(rate(windows_cpu_time_total{instance=~\"$server.*\", mode=\"idle\"}[$__rate_interval]))",
     "legendFormat": "idle"
    }
   ]
  },
  {
   "title": "CPU load per process",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (process) (rate(windows_process_cpu_time_total{instance=~\"$server.*\", process !~\"Idle\"}[$__rate_interval]))",
     "legendFormat": "{{ process }}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "windows_cs_physical_memory_bytes{instance=~\"$server.*\"} - windows_os_physical_memory_free_bytes{instance=~\"$server.*\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "windows_os_physical_memory_free_bytes{instance=~\"$server.*\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "100 - (windows_os_physical_memory_free_bytes{instance=~\"$server.*\"} / windows_cs_physical_memory_bytes{instance=~\"$server.*\"}) * 100",
     "legendFormat": "Used %"
    }
   ]
  },
  {
   "title": "Average commit bytes per process",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by (process) (windows_process_private_bytes{instance=~\"$server.*\", process=~\".*\"})",
     "legendFormat": "{{ process }}"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Hard drive load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(windows_logical_disk_write_bytes_total{instance=~\"$server.*\", volume !~\"HarddiskVolume.+\"}[$__rate_interval])",
     "legendFormat": "Write {{volume}}"
    },
    {
     "expr": "irate(windows_logical_disk_read_bytes_total{instance=~\"$server.*\", volume !~\"HarddiskVolume.+\"}[$__rate_interval])",
     "legendFormat": "Read {{volume}}"
    }
   ]
  },
  {
   "title": "I/O bytes total per process",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by (process) (rate(windows_process_io_bytes_total{instance=~\"$server.*\", mode=\"read\"}[$__rate_interval])) > 0",
     "legendFormat": "{{ process }} read"
    },
    {
     "expr": "avg by (process) (rate(windows_process_io_bytes_total{instance=~\"$server.*\", mode=\"write\"}[$__rate_interval])) > 0",
     "legendFormat": "{{ process }} write"
    }
   ]
  },
  {
   "title": "Hard disk i/o ops total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(windows_logical_disk_split_ios_total{instance=~\"$server.*\", volume !~\"HarddiskVolume.+\"}[$__rate_interval])",
     "legendFormat": "i/o {{volume}}"
    }
   ]
  },
  {
   "title": "Hard disk latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(windows_logical_disk_write_latency_seconds_total{instance=~\"$server.*\", volume !~\"HarddiskVolume.+\"}[$__rate_interval])",
     "legendFormat": "Latency {{volume}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Traffic bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(windows_net_bytes_sent_total{instance=~\"$server.*\"}[$__rate_interval])",
     "legendFormat": "Sent {{nic}}"
    },
    {
     "expr": "rate(windows_net_bytes_received_total{instance=~\"$server.*\"}[$__rate_interval])",
     "legendFormat": "Received {{nic}}"
    }
   ]
  },
  {
   "title": "Network discarded/error packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(windows_net_packets_outbound_discarded_total{instance=~\"$server.*\", nic!~\"isatap.+\"}[$__rate_interval]) + irate(windows_net_packets_outbound_errors_total{instance=~\"$server.*\"}[$__rate_interval])",
     "legendFormat": "Sent {{nic}}"
    },
    {
     "expr": "irate(windows_net_packets_received_discarded_total{instance=~\"$server.*\", nic!~\"isatap.+\"}[$__rate_interval]) + irate(windows_net_packets_received_errors_total{instance=~\"$server.*\"}[$__rate_interval])",
     "legendFormat": "Received {{nic}}"
    }
   ]
  }
 ]
}