{
 "title": "KIOSK",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Client",
    "query": "SELECT name FROM clients_client order by name"
   },
   { "name": "Sites", "query": "SELECT name FROM clients_site" },
   {
    "name": "Agents_HostName",
    "query": "SELECT \nhostname\nFROM \nagents_agent\n\n\n"
   },
   {
    "name": "Message_Severity",
    "query": "SELECT \nalerts_alert.severity\n  FROM alerts_alert"
   }
  ]
 },
 "panels": [
  {
   "title": "Agentes",
   "type": "stat",
   "description": "Number of clients connected to TRMM",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM agents_agent\nwhere \n  site_id IN (SELECT id FROM clients_site WHERE site_id IN (SELECT id FROM clients_site WHERE name IN ($Sites))) and\n  site_id IN (SELECT id FROM clients_site WHERE client_id IN (SELECT id FROM clients_client WHERE name IN ($Client)))\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Erros",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  count(*) as \"error\"\r\n  FROM alerts_alert\r\nWhere\r\n alerts_alert.severity = 'error'  \r\n AND alerts_alert.resolved = false"
    }
   ]
  },
  {
   "title": "Avisos",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  count(*)\r\n  FROM alerts_alert\r\nWhere\r\n alerts_alert.severity = 'warning' \r\n AND alerts_alert.resolved = false"
    }
   ]
  },
  {
   "title": "Informações",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  count(*)\r\n  FROM alerts_alert\r\nWhere\r\n alerts_alert.severity = 'info' \r\n AND alerts_alert.resolved = false"
    }
   ]
  },
  {
   "title": "Memoria Abaixo de 8GB",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  count(*)\r\n  FROM agents_agent\r\nWhere\r\n agents_agent.total_ram < 8"
    }
   ]
  },
  {
   "title": "Tela Azul da Morte",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  count(*)\r\n  FROM checks_check\r\nWhere\r\n checks_check.status = 'failing'\r\n and checks_check.name = 'Tela Azul - BugCheck'\r\n "
    }
   ]
  },
  {
   "title": "Antivirus",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "diffperc" ] } },
   "targets": [
    {
     "rawSql": "  SELECT \r\n  s.software->0->>'name' as \"Antivirus\",\r\n  count(*) as \"count\",\r\n  array_agg(aa.hostname) as \"Dispositivos\"\r\n  FROM software_installedsoftware as s\r\n  inner join agents_agent aa on s.agent_id = aa.id\r\n  inner join clients_site cs on aa.site_id = cs.id \r\n  inner join clients_client cc on cs.client_id = cc.id\r\n  WHERE \r\n    s.software->0->>'name' LIKE '%Avast%'\r\n    or s.software->0->>'name' LIKE '%Bitdefender%'\r\n  \r\n    \r\nGroup by \"Antivirus\"\r\nOrder by \"count\" desc\r\n  "
    }
   ]
  },
  {
   "title": "Memoria Abaixo de 8GB",
   "type": "table",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 3 },
   "targets": [
    {
     "rawSql": "select \r\ncc.\"name\" as \"Cliente\",\r\ncs.\"name\" as \"Site\",\r\nagente.hostname as \"Dispositivo\",\r\nSUBSTRING(agente.operating_system,',(.*)bit') as \"Architeture\",\r\nagente.total_ram as \"Memoria\"\r\nfrom agents_agent as agente \r\ninner join clients_site cs on agente.site_id = cs.id \r\ninner join clients_client cc on cs.client_id = cc.id \r\nwhere agente.total_ram < 8\r\norder by \"Memoria\""
    }
   ]
  },
  {
   "title": "Memory type",
   "type": "bargauge",
   "description": "List all installed memory",
   "gridPos": { "h": 17, "w": 6, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "  SELECT \r\n  count(*) as \"count\",\r\n  concat((total_ram),' Gb') as \"Size Memory\"\r\n  FROM agents_agent\r\nINNER JOIN clients_site on site_id = clients_site.id\r\n\r\nWHERE\r\n site_id IN (SELECT id FROM clients_site WHERE client_id IN (SELECT id FROM clients_client WHERE name IN ($Client)))\r\nAND site_id IN (SELECT id FROM clients_site WHERE site_id IN (SELECT id FROM clients_site WHERE name IN ($Sites)))\r\nGroup by \"Size Memory\"\r\nOrder by \"count\" desc\r\n  "
    }
   ]
  },
  {
   "title": "Windows type",
   "type": "bargauge",
   "description": "List all Windows installed",
   "gridPos": { "h": 17, "w": 6, "x": 6, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "  SELECT \r\n  count(*) as \"count\",\r\n  SUBSTRING(agents_agent.operating_system,'(.*)bit') AS \"Operating System\"\r\n  FROM agents_agent\r\nINNER JOIN clients_site on site_id = clients_site.id\r\n\r\nWHERE site_id IN (SELECT id FROM clients_site WHERE client_id IN (SELECT id FROM clients_client WHERE name IN ($Client)))\r\nAND site_id IN (SELECT id FROM clients_site WHERE site_id IN (SELECT id FROM clients_site WHERE name IN ($Sites)))\r\nGroup by \"Operating System\"\r\nOrder by \"count\" desc\r\n  "
    }
   ]
  },
  {
   "title": "Processor type",
   "type": "bargauge",
   "description": "List all installed processors",
   "gridPos": { "h": 17, "w": 8, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "  SELECT \r\n  count(*) as \"count\",\r\n  wmi_detail->'cpu'->0->0->>'Name' as \"CPU Name\"\r\n  FROM agents_agent\r\nINNER JOIN clients_site on site_id = clients_site.id\r\n\r\nWHERE site_id IN (SELECT id FROM clients_site WHERE client_id IN (SELECT id FROM clients_client WHERE name IN ($Client)))\r\nAND site_id IN (SELECT id FROM clients_site WHERE site_id IN (SELECT id FROM clients_site WHERE name IN ($Sites)))\r\nGroup by \"CPU Name\"\r\nOrder by \"count\" desc\r\n  "
    }
   ]
  },
  {
   "title": "Information on Client or selected site",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 }
  },
  {
   "title": "Error message",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  alert_time as \"Date Message\",\r\n  alerts_alert.severity,\r\n  message as \"Messages\"\r\n  FROM alerts_alert\r\nWHERE \r\n alerts_alert.severity = 'warning'\r\n AND alerts_alert.resolved = false"
    }
   ]
  },
  {
   "title": "Error message",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  alert_time as \"Date Message\",\r\n  alerts_alert.severity,\r\n  message as \"Messages\"\r\n  FROM alerts_alert\r\nWHERE \r\n alerts_alert.severity = '$Message_Severity'\r\n AND alerts_alert.resolved = false"
    }
   ]
  },
  {
   "title": "Client last reboot",
   "type": "table",
   "description": "Number of clients connected to TRMM",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 41 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  clients_site.name AS \"Site\",\r\n  hostname AS \"Hostname\",\r\n  description as \"description\",\r\n  last_seen AS \"Last Response\",\r\n  to_timestamp(boot_time) AS \"Last Reboot\"\r\nFROM agents_agent\r\nINNER JOIN clients_site on site_id = clients_site.id\r\n\r\nWHERE \r\nsite_id IN (SELECT id FROM clients_site WHERE client_id IN (SELECT id FROM clients_client WHERE name IN ($Client)))\r\nAND site_id IN (SELECT id FROM clients_site WHERE site_id IN (SELECT id FROM clients_site WHERE name IN ($Sites)))"
    }
   ]
  },
  {
   "title": "OS distribution",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "  select (\r\nSELECT\r\n  count(*)\r\n  FROM agents_agent\r\nWhere\r\n  SUBSTRING(agents_agent.operating_system,POSITION(',' in agents_agent.operating_system)+2,2) = '64' and\r\n  site_id IN (SELECT id FROM clients_site WHERE site_id IN (SELECT id FROM clients_site WHERE name IN ($Sites))) and\r\n  site_id IN (SELECT id FROM clients_site WHERE client_id IN (SELECT id FROM clients_client WHERE name IN ($Client)))) as \"64 Bits\",\r\n\r\n  (SELECT\r\n  count(*)\r\n  FROM agents_agent\r\nWhere\r\n  SUBSTRING(agents_agent.operating_system,POSITION(',' in agents_agent.operating_system)+2,2) = '32' and\r\n   site_id IN (SELECT id FROM clients_site WHERE site_id IN (SELECT id FROM clients_site WHERE name IN ($Sites))) and\r\n  site_id IN (SELECT id FROM clients_site WHERE client_id IN (SELECT id FROM clients_client WHERE name IN ($Client)))) as \"32 Bits\" "
    }
   ]
  }
 ]
}